all:
	g++ -Wall -Wextra -std=c++11 -DDEBUG -DDEBUG_TIMER -DDEBUG_TP_DSC *.cpp -o main && ./main

fulldbg:
	g++ -Wall -Wextra -std=c++11 -DDEBUG -DDEBUG_TIMER -DDEBUG_ITER -DDEBUG_NODE -DDEBUG_TP_DSC *.cpp -o main && ./main


